### PR TITLE
removed the patch to ice cube

### PR DESCRIPTION
**Pull request by jmatsuba**
- Appears to no longer be needed in Rails 4
- Is causing exceptions as the serialize module has significantly changed between Rails 3, 4

### CODE REVIEW

**Review by scottbarrow — APPROVED** [review]
as per pairing session, the method doesn't seem to be called in Rails 3, and 4 the serializer `default_value?` passes nil to the equality operator

**Comment by avit** [comment]
Looks good: the original patch was from before IceCube itself implemented `def ==` internally:

2010: https://github.com/avit/schedule_attributes/commit/3711f96a35c3adf4d63da8cf1ba613cdefe63c4f#diff-37bd2a8808a920897fbdd505e7d1c23dR96
2011: https://github.com/seejohnrun/ice_cube/commit/42924cd1fb9a12d1428ad4e9219191aca0401ed7#diff-e7a9a7e60e930d8a8c2e63f558b8d969R9

Please make this pull request against avit/schedule_attributes@master instead of this master branch and I'll publish a gem update from there. (I don't want to deal with redirecting it here for now but can do later if Guestfolio wants to take over maintenance.)

**Review by avit — APPROVED** [review]

**Comment by avit** [comment]
Better yet, merge all these to an integration branch here (instead of polluting master) until everything is figured out and then you can make a single PR for "rails 4 compatibility" to be published.

**Comment by jmatsuba** [comment]
Merged into integration branch. Per avit.

**Pull request closed without merging**
